### ISSUE TITLE
Increase maximum playback time > 120 mins

### ISSUE THREAD

**Issue by DmnzH** [jbinkley60/service.autostop#1] opened 2022-01-15 09:38 UTC
I really enjoyed using this plugin, but at the moment, maximum playback time is currently limited to 120 mins. With many feature film length more than 120 mins, it's really easy to get interrupted during viewing.

Increasing the maximum playback time to 180 mins or maybe more would be very useful.

**Comment by jbinkley60** [comment] 2022-01-15 10:13
Thanks for the suggestion and I am happy to make the change but can you help me understand the use case a little better ?  The maximum playback timer is like an alarm clock snooze timer where the addon will stop playback after a predetermined time.  Are you thinking you want it to stop maybe after the movie completes or something else ?  Also, one thing I noticed is that the addon maximum playback timer doesn't stop the timer if you pause a movie during playback.  So I can easily change it so for example if you have it set to say 120 minutes but during that time you pause the playback for 10 minutes, I can have the addon add the 10 minutes to the timer counter.

**Comment by DmnzH** [comment] 2022-01-15 10:51
My use case is for when I play youtube videos with auto play next videos, or when playing a long playlist. I'd like the auto stop to stop the playback in case I snooze, which will then activate kodi's screensaver and put the TV to sleep mode.

But when watching featured film, it stops the playback at 120 mins. It's a minor issue since I can just resume the playback, but I'd be perfect if I can set it to 150 mins, which should be plenty for 99.9% of films.

**Comment by DmnzH** [comment] 2022-01-15 11:01
That pause idea it's actually quite cool. Not sure if this is possible, but on previous Kodi, I have similar sleep timer add-on which displays a 30 seconds countdown before it stops playback, and if I still want to continue the playback, I can press any button on my remote to reset/extend the stop timer.

Whoops, I accidentally closed the issue.

**Comment by DmnzH** [comment] 2022-01-15 11:07
Whoops, I accidentally closed the issue.

**Comment by jbinkley60** [comment] 2022-01-15 17:04
How about if I add these three enhancements ?

1.  Extend the maximum sleep timer to 180 minutes
2.  Add a progress notification box to let you know when you are nearing the sleep timer value which will stop playback.  I'll add a user setting of 0, 30 and 60 seconds.  0 means no notification.  The other options would be prior to stopping playback.  One question here is I presume you'll want to be able to click a button in the progress notification to extend the sleep timer ?  If so how long ?  I can make a setting for that like 15, 30, 60 minutes ?  Let me know your thoughts.
3. Add an option for better handling paused playback during the sleep timer.  I am thinking of a setting which has three options.  First, do nothing when paused and the sleep timer is just fixed to what you set (unless #2 above happens).  Second, stop the sleep timer when playback is paused.  This is what I described above.  If you pause playback for say 10 minutes during the sleep timer period the sleep timer will be extended by 10 minutes.  Third is reset the sleep time counter back to zero once playback resumes.  So if the sleep timer is set for 30 minutes and you pause playback during that period, once you restart playback the timer resets back to 30 minutes.

Let me know what you think of these three enhancements.  It would take me a couple of days to have a test release with all of them.


Jeff

**Comment by DmnzH** [comment] 2022-01-15 21:09
Sounds great. As for the timer extension I am thinking either an options of 15, 30, 60, 120 and 180 mins, or make it to have the same options as the sleep timer.

**Comment by jbinkley60** [comment] 2022-01-17 10:13
I've posted a test release[ here](https://github.com/jbinkley60/service.autostop/tree/Test) .  It has all of the updates.

1.0.2

-  Extended eleep timer settings to 180 minutes
-  Added pause sleep timer adjust option to select what
   to do with the sleep timer when playback is paused.
     None - Do nothing and sleep counter continues
     Pause - Pause sleep timer
     Reset - Reset sleep timer to beginning
-  Added 0 -180 secs adjustable GUI sleep timer notification 
   feature with adjustable sleep timer extension.
-  Added event logging option to aid troubleshooting  

Please try it and provide any testing feedback.

Thanks,

Jeff

**Comment by DmnzH** [comment] 2022-01-17 12:28
I gave it some testing, everything looks good, but there is one minor issue with the notification countdown. If I let the countdown to lapse, video playback is stopped, but subsequent video playback doesn't have countdown anymore. I need to restart kodi to have the countdown to appear again.

Step to reproduce:
Sleep Timer: 10 mins
Countdown timer: 30 secs
Extend Timer: 10 mins

1. Playback video, wait 10 mins.
2. Countdown appears, wait 30 secs for countdown to lapse.
3. Video playback stopped. - Correct behaviour -
4. Play another video, wait 10 mins.
5. No countdown, Playback stopped without countdown. - Incorrect -
6. Try another video, wait 10 mins.
7. Still no countdown. - Incorrect -

**Comment by jbinkley60** [comment] 2022-01-17 13:04
Thanks for the catch and clear instructions on how to reproduce.  The issue has been fixed in [1.0.2b](https://github.com/jbinkley60/service.autostop/tree/Test) .  It was a simple notification flag which gets sets when the sleep timer notification starts.  It was being cleared when you extended the timer via the notification window or when Kodi restarted.  It wasn't being cleared when the Autostop addon stopped a video.  1.0.2b fixes that issue.

Thanks,

Jeff

**Comment by jbinkley60** [comment] 2022-01-18 11:52
test release [version 1.0.2c](https://github.com/jbinkley60/service.autostop/tree/Test) has been uploaded.   It fixes an issue caused by the extension timer settings having an option and default value of 0 minutes.  This caused a looping condition in the GUI for the user and practically didn't make any sense on why someone would extend playback for 0 minutes.  The minimum and default values are now both 10 minutes.

Jeff

**Comment by DmnzH** [comment] 2022-01-19 04:01
Perfect, I've been testing 1.0.2b and 1.0.2c, they seem to work fine.

**Comment by jbinkley60** [comment] 2022-01-19 12:13
I've uploaded one more test release, [v1.0.2d](https://github.com/jbinkley60/service.autostop/tree/Test) .    There are 2 main differences with this release.

- Under the extension time setting there is now an option now called variable.  If you set it to variable when you hit cancel on the progress bar it will bring up a dialog box so you can select the amount of time to extend the sleep timer.  I've set the current selection options from 10-90 minutes.
- Implementing this requested feature forced me to fix an existing issue. where the extension time was only the amount of played time if the played time was less than the extension time setting.  Now the extension times are correct regardless of the play times.  


Jeff

**Comment by jbinkley60** [comment] 2022-01-20 17:28
I posted version [1.0.2e](https://github.com/jbinkley60/service.autostop/tree/Test) today.  This version has the following changes and will be the official 1.0.2 release unless a bug is found in the next week or so.
 

- Eliminated duplicate code between paused playback and sleep timer functions.  Also simplified logging and reduced overhead.
- Added a feature when the sleep timer extension is set for variable the user will be given an option to immediately stop playback, in addition to the extension times  This feature is enabled via a setting but is disabled by default.


Jeff

**Closed as completed** 2022-02-01 20:03 UTC
